### ISSUE TITLE
Platforms besides Windows will not load, due to the paths being incompatible

### ISSUE THREAD

**Issue by fmbearmf** [TheRealHiThere/Basic-Python-Chess-Engine#2]
Platforms such besides Windows are not supported by this engine.

- [x] #1 Fix the hardcoded paths not working on other platforms

PR #1 will fix this by adding OS detection, and changing paths if you're not on Windows.

Important Contributor(s) for this issue:
@TheRealHiThere

**Comment by TheDevConnor** [comment]
Thx! Man I really appreciate it.
